- name: Download, install kafka on all servers
  hosts: all
  tasks:
  - name: Install Java 1.8
    become: yes
    yum:
      name:
      - java-1.8.0
      state: present
  - name: Uninstall Java 1.7
    become: yes
    ignore_errors: yes
    yum:
      name: 
      - java-1.7.0-openjdk
      state: absent
  - name: Download Kafka 
    get_url: 
      url: https://downloads.apache.org/kafka/2.6.0/kafka_2.12-2.6.0.tgz 
      dest: ~/.
  - name: Unpack the tar
    shell: tar -xzvf ~/kafka_2.12-2.6.0.tgz 

  - name: Copy Kafka into place
    shell: mv ~/kafka_2.12-2.6.0  ~/kafka

  - name: make log directory
    shell: cd kafka && mkdir logs
    
- name: Zookeeper
  hosts: zookeeper
  tasks:
    - name: Start server
      shell: nohup ~/kafka/bin/zookeeper-server-start.sh ~/kafka/config/zookeeper.properties &

- hosts: broker0
  tasks:
  - name: set up server0 config
    copy:
      src: ./server_configs/server0/server.properties
      dest: ~/kafka/config
      force: yes

- hosts: broker1
  tasks:
  - name: set up server1 config
    copy:
      src: ./server_configs/server1/server.properties
      dest: ~/kafka/config
      force: yes

- hosts: broker2
  tasks:
  - name: set up server2 config
    copy:
      src: ./server_configs/server2/server.properties
      dest: ~/kafka/config
      force: yes

- name: start brokers
  hosts: brokers
  tasks:
    - name: Start server
      shell: nohup ~/kafka/bin/kafka-server-start.sh ~/kafka/config/server.properties &
